#include "core/i18n.h"

#include <QCoreApplication>
#include <QGuiApplication>
#include <QLibraryInfo>
#include <QStringList>
#include <QTranslator>

#include "data/setting_repository.h"

namespace app::core {

namespace {

QTranslator* s_appTranslator = nullptr;
QTranslator* s_qtTranslator = nullptr;

// Unload and destroy the translators installed by a previous applyLanguage().
// The pointers are held in file-scope statics because QTranslator must outlive
// its installTranslator() call and stay owned for the whole process.
void unloadTranslators()
{
    if (s_appTranslator != nullptr) {
        QCoreApplication::removeTranslator(s_appTranslator);
        delete s_appTranslator;
        s_appTranslator = nullptr;
    }
    if (s_qtTranslator != nullptr) {
        QCoreApplication::removeTranslator(s_qtTranslator);
        delete s_qtTranslator;
        s_qtTranslator = nullptr;
    }
}

bool isSupported(const QString& code)
{
    return supportedLanguages().contains(code);
}

} // namespace

QStringList supportedLanguages()
{
    return {QStringLiteral("ar"), QStringLiteral("fr"), QStringLiteral("en")};
}

QString defaultLanguage()
{
    return QStringLiteral("ar");
}

bool applyLanguage(const QString& code)
{
    unloadTranslators();

    if (!isSupported(code)) {
        return false;
    }

    // Application catalogue: generated by qt_add_translations and embedded in
    // the binary under the "/i18n" resource prefix.
    auto* appTranslator = new QTranslator;
    if (appTranslator->load(QStringLiteral(":/i18n/mahali_%1.qm").arg(code))) {
        QCoreApplication::installTranslator(appTranslator);
        s_appTranslator = appTranslator;
    } else {
        delete appTranslator;
    }

    // Qt's own strings (standard buttons, shortcuts, file dialogs).
    auto* qtTranslator = new QTranslator;
    const QString qtPath = QLibraryInfo::path(QLibraryInfo::TranslationsPath);
    if (qtTranslator->load(QStringLiteral("qtbase_%1").arg(code), qtPath)) {
        QCoreApplication::installTranslator(qtTranslator);
        s_qtTranslator = qtTranslator;
    } else {
        delete qtTranslator;
    }

    // Pin the reading direction. Guarded because the data-layer tests run with a
    // plain QCoreApplication (QTEST_GUILESS_MAIN) and have no layout to set.
    if (auto* gui = qobject_cast<QGuiApplication*>(QCoreApplication::instance())) {
        gui->setLayoutDirection(
            code == QStringLiteral("ar") ? Qt::RightToLeft : Qt::LeftToRight);
    }

    return s_appTranslator != nullptr;
}

QString currentLanguage(app::data::Database& db)
{
    data::SettingRepository settings(db);
    const QString code =
        settings.value(QStringLiteral("language")).value_or(QString());
    if (code.isEmpty() || !isSupported(code)) {
        return defaultLanguage();
    }
    return code;
}

} // namespace app::core
