name: Build Windows

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          arch: win64_msvc2022_64
          modules: 'qthttpserver'
          cache: true
      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: cmake --build build --config Release --target mahali-desktop
      - name: Deploy
        shell: pwsh
        run: |
          mkdir dist
          $exe = Get-ChildItem -Recurse -Filter "mahali-desktop.exe" build | Select-Object -First 1
          Copy-Item $exe.FullName dist\
          windeployqt --release "dist\mahali-desktop.exe"
      - name: Zip
        run: Compress-Archive -Path dist\* -DestinationPath mahali-msvc.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mahali-msvc
          path: mahali-msvc.zip
